version: '3.4'

services:        # Root level
  catalogdb:     # Service under services
    image: postgres:15

  basketdb:
    image: postgres:15

  distributedcache:
    image: redis

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:         # Root level (NOT under services)
  postgres_catalog:
  postgres_basket:
   



