version: '3.4'

services:        # Root level
  catalogdb:     # Service under services
    image: postgres:15

  basketdb:
    image: postgres:15

  distributedcache:
    image: redis

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:         # Root level (NOT under services)
  postgres_catalog:
  postgres_basket:
   

